name: Build the RFC from XML
on:
  push:
    branches:
      - rfc
    tags:
      - rfc/**
  pull_request:
    branches:
      - rfc

jobs:
  build:
    name: Build RFC
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install xml2rfc (and Python dependencies)
      run: |
        python -m pip install --upgrade pip
        pip install xml2rfc==3.0
    - name: Process XML
      run: |
        mkdir output
        xml2rfc -p output --text --html path2globus.xml
    - name: Upload RFC Text
      uses: actions/upload-artifact@v2
      with:
        name: path2globus.txt
        path: output/path2globus.txt
    - name: Upload RFC HTML
      uses: actions/upload-artifact@v2
      with:
        name: path2globus.html
        path: output/path2globus.html
